[project]
name = 'practice'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.asserts]
path = 'contracts/asserts.clar'
clarity_version = 2
epoch = 2.5

[contracts.hello]
path = 'contracts/hello.clar'
clarity_version = 2
epoch = 2.5

[contracts.private-function-Example]
path = 'contracts/private-function-Example.clar'
clarity_version = 2
epoch = 2.5

[contracts.public-function-Example]
path = 'contracts/public-function-Example.clar'
clarity_version = 2
epoch = 2.5

[contracts.read-only-function]
path = 'contracts/read-only-function.clar'
clarity_version = 2
epoch = 2.5

[contracts.try]
path = 'contracts/try.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
